const SET_AUTH_TRUE = 'SET_AUTH_TRUE';
const SET_AUTH_FALSE = 'SET_AUTH_FALSE';
const DELETE_TASK = 'DELETE_TASK';
const ADD_TASK = 'ADD_TASK';
const GET_TASK = 'GET_TASK';
const CHECK_TASK = 'CHECK_TASK';
const SET_STATE = 'SET_STATE';
const SET_DATA_TO_STORE = 'SET_DATA_TO_STORE';
const UPDATE_TASK = 'UPDATE_TASK';
const DELETE_STATE = 'DELETE_STATE';

export {
  SET_AUTH_TRUE,
  SET_AUTH_FALSE,
  DELETE_TASK,
  ADD_TASK,
  CHECK_TASK,
  SET_STATE,
  SET_DATA_TO_STORE,
  GET_TASK,
  UPDATE_TASK,
  DELETE_STATE,
};
